### ISSUE TITLE
Green area.

### ISSUE THREAD

**Issue by MosheMikhael** [Pandas-Team/Autonomous-Vehicle-Environment-Perception#1]
Good day!
Beautiful project, I'm trying to run in сolab on my video and get unsatisfactory results, I guess because of the low quality of the picture + bad road markings, isn't it?
What does the green area on the picture mean?
![image](https://user-images.githubusercontent.com/45757436/114623406-e7fd0880-9cb7-11eb-92df-f018b522c0da.png)

**Comment by miladsoltany** [comment]
Dear Moshe,
Thank you for your interest in our project.
The green area indicates crosswalks on the street. We used classic computer vision algorithms used for this particular task, and the thresholds are hand-chosen. Therefore, it's not robust against low-quality images. We are, however, trying to fix that in near future.

**Comment by MosheMikhael** [comment]
One little thing, notice that in **PINet.py**, in the description of the **LaneDetection()** class, in the **Testing(self, frame, mask)** function there is an unpleasant line: **ti[0] = cv2.resize(ti[0], (1280,720))**.
If we run on a video with a different size, there will be an _AssertationError_ somewhere in the mask overlay process.

Good luck!

**Comment by miladsoltany** [comment]
@MosheMikhael Thanks for noticing the issue and telling us about it, we will soon work on fixing the issues you mentioned.

**Comment by miladsoltany** [comment]
Dear @MosheMikhael, 
I added a quick fix to the assertion error problem you mentioned.
Thank you for your feedback.
