### ISSUE TITLE
Frame rate is too low

### ISSUE THREAD

**Issue by LHT130** [Pandas-Team/Autonomous-Vehicle-Environment-Perception#2]
How to improve the frame rate of the output video, my output display interface is only about 2 frames

**Comment by amirhossein-kz** [comment]
Dear @LHT130 

Thank you for being so interested in our project. We will update the code soon. This is the previous version. However, it depends on your GPU model. This version should give you around 5 or 6 FPS on Tesla T4.

**Comment by LHT130** [comment]
> 

Thank you for your answer.
Good Luck!
